module.exports = {
	COMMUNITY_CHAT:"COMMUNITY_CHAT",
	USER_CONNECTED:"USER_CONNECTED",
	MASSAGE_RECIEVED:"MASSAGE_RECIEVED",
	MESSAGE_SENT:"MESSAGE_SENT",
	USER_DISCONECTED:"USER_DISCONECTED",
	TYPING:"TYPING",
	VERIFY_USER:"VERIFY_USER",
	LOGOUT:"LOGOUT"
}